# Generated by Django 5.1.4 on 2025-01-02 10:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
